#[doc = "Capture High Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CAPTURE_H(pub u32);
impl CAPTURE_H {
    #[doc = "A read reflects the value of the upper 10 bits of the central 42-bits EVTIMER at the time the last capture signal was generated by the CPU (using CMSIS C function \"__SEV();\")."]
    #[must_use]
    #[inline(always)]
    pub const fn CAPTURE_VALUE(&self) -> u16 {
        let val = (self.0 >> 0usize) & 0x03ff;
        val as u16
    }
    #[doc = "A read reflects the value of the upper 10 bits of the central 42-bits EVTIMER at the time the last capture signal was generated by the CPU (using CMSIS C function \"__SEV();\")."]
    #[inline(always)]
    pub const fn set_CAPTURE_VALUE(&mut self, val: u16) {
        self.0 = (self.0 & !(0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize);
    }
}
impl Default for CAPTURE_H {
    #[inline(always)]
    fn default() -> CAPTURE_H {
        CAPTURE_H(0)
    }
}
impl core::fmt::Debug for CAPTURE_H {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAPTURE_H")
            .field("CAPTURE_VALUE", &self.CAPTURE_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for CAPTURE_H {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "CAPTURE_H {{ CAPTURE_VALUE: {=u16:?} }}",
            self.CAPTURE_VALUE()
        )
    }
}
#[doc = "Capture Low Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct CAPTURE_L(pub u32);
impl CAPTURE_L {
    #[doc = "A read reflects the value of the lower 32 bits of the central 42-bits EVTIMER at the time the last capture signal was generated by the CPU (using CMSIS C function \"__SEV();\")."]
    #[must_use]
    #[inline(always)]
    pub const fn CAPTURE_VALUE(&self) -> u32 {
        let val = (self.0 >> 0usize) & 0xffff_ffff;
        val as u32
    }
    #[doc = "A read reflects the value of the lower 32 bits of the central 42-bits EVTIMER at the time the last capture signal was generated by the CPU (using CMSIS C function \"__SEV();\")."]
    #[inline(always)]
    pub const fn set_CAPTURE_VALUE(&mut self, val: u32) {
        self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
    }
}
impl Default for CAPTURE_L {
    #[inline(always)]
    fn default() -> CAPTURE_L {
        CAPTURE_L(0)
    }
}
impl core::fmt::Debug for CAPTURE_L {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("CAPTURE_L")
            .field("CAPTURE_VALUE", &self.CAPTURE_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for CAPTURE_L {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "CAPTURE_L {{ CAPTURE_VALUE: {=u32:?} }}",
            self.CAPTURE_VALUE()
        )
    }
}
#[doc = "EVTIMER High Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct EVTIMERH(pub u32);
impl EVTIMERH {
    #[doc = "A read reflects the current value of the upper 10 bits of the 42-bits EVTIMER. Note there is only one EVTIMER, readable from all domains."]
    #[must_use]
    #[inline(always)]
    pub const fn EVTIMER_COUNT_VALUE(&self) -> u16 {
        let val = (self.0 >> 0usize) & 0x03ff;
        val as u16
    }
    #[doc = "A read reflects the current value of the upper 10 bits of the 42-bits EVTIMER. Note there is only one EVTIMER, readable from all domains."]
    #[inline(always)]
    pub const fn set_EVTIMER_COUNT_VALUE(&mut self, val: u16) {
        self.0 = (self.0 & !(0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize);
    }
}
impl Default for EVTIMERH {
    #[inline(always)]
    fn default() -> EVTIMERH {
        EVTIMERH(0)
    }
}
impl core::fmt::Debug for EVTIMERH {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EVTIMERH")
            .field("EVTIMER_COUNT_VALUE", &self.EVTIMER_COUNT_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for EVTIMERH {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "EVTIMERH {{ EVTIMER_COUNT_VALUE: {=u16:?} }}",
            self.EVTIMER_COUNT_VALUE()
        )
    }
}
#[doc = "EVTIMER Low Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct EVTIMERL(pub u32);
impl EVTIMERL {
    #[doc = "A read reflects the current value of the lower 32 bits of the 42-bits EVTIMER. Note there is only one EVTIMER, readable from all domains."]
    #[must_use]
    #[inline(always)]
    pub const fn EVTIMER_COUNT_VALUE(&self) -> u32 {
        let val = (self.0 >> 0usize) & 0xffff_ffff;
        val as u32
    }
    #[doc = "A read reflects the current value of the lower 32 bits of the 42-bits EVTIMER. Note there is only one EVTIMER, readable from all domains."]
    #[inline(always)]
    pub const fn set_EVTIMER_COUNT_VALUE(&mut self, val: u32) {
        self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
    }
}
impl Default for EVTIMERL {
    #[inline(always)]
    fn default() -> EVTIMERL {
        EVTIMERL(0)
    }
}
impl core::fmt::Debug for EVTIMERL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("EVTIMERL")
            .field("EVTIMER_COUNT_VALUE", &self.EVTIMER_COUNT_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for EVTIMERL {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "EVTIMERL {{ EVTIMER_COUNT_VALUE: {=u32:?} }}",
            self.EVTIMER_COUNT_VALUE()
        )
    }
}
#[doc = "Match High Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct MATCH_H(pub u32);
impl MATCH_H {
    #[doc = "The value written (upper 10 bits) to the MATCH (L/H) register pair is compared against the central EVTIMER. When a match occurs, an interrupt request is generated if enabled."]
    #[must_use]
    #[inline(always)]
    pub const fn MATCH_VALUE(&self) -> u16 {
        let val = (self.0 >> 0usize) & 0x03ff;
        val as u16
    }
    #[doc = "The value written (upper 10 bits) to the MATCH (L/H) register pair is compared against the central EVTIMER. When a match occurs, an interrupt request is generated if enabled."]
    #[inline(always)]
    pub const fn set_MATCH_VALUE(&mut self, val: u16) {
        self.0 = (self.0 & !(0x03ff << 0usize)) | (((val as u32) & 0x03ff) << 0usize);
    }
}
impl Default for MATCH_H {
    #[inline(always)]
    fn default() -> MATCH_H {
        MATCH_H(0)
    }
}
impl core::fmt::Debug for MATCH_H {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MATCH_H")
            .field("MATCH_VALUE", &self.MATCH_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for MATCH_H {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(f, "MATCH_H {{ MATCH_VALUE: {=u16:?} }}", self.MATCH_VALUE())
    }
}
#[doc = "Match Low Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct MATCH_L(pub u32);
impl MATCH_L {
    #[doc = "The value written to the MATCH (L/H) register pair is compared against the central EVTIMER. When a match occurs, an interrupt request is generated if enabled."]
    #[must_use]
    #[inline(always)]
    pub const fn MATCH_VALUE(&self) -> u32 {
        let val = (self.0 >> 0usize) & 0xffff_ffff;
        val as u32
    }
    #[doc = "The value written to the MATCH (L/H) register pair is compared against the central EVTIMER. When a match occurs, an interrupt request is generated if enabled."]
    #[inline(always)]
    pub const fn set_MATCH_VALUE(&mut self, val: u32) {
        self.0 = (self.0 & !(0xffff_ffff << 0usize)) | (((val as u32) & 0xffff_ffff) << 0usize);
    }
}
impl Default for MATCH_L {
    #[inline(always)]
    fn default() -> MATCH_L {
        MATCH_L(0)
    }
}
impl core::fmt::Debug for MATCH_L {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("MATCH_L")
            .field("MATCH_VALUE", &self.MATCH_VALUE())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for MATCH_L {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(f, "MATCH_L {{ MATCH_VALUE: {=u32:?} }}", self.MATCH_VALUE())
    }
}
#[doc = "OS_EVENT TIMER Control Register."]
#[repr(transparent)]
#[derive(Copy, Clone, Eq, PartialEq)]
pub struct OSEVENT_CTRL(pub u32);
impl OSEVENT_CTRL {
    #[doc = "This bit is set when a match occurs between the central 42-bits EVTIMER and the value programmed in the match-register pair. This bit is cleared by writing a '1'. Writes to clear this bit are asynchronous. It should be done before a new match value is written into the MATCH_L/H registers."]
    #[must_use]
    #[inline(always)]
    pub const fn OSTIMER_INTRFLAG(&self) -> bool {
        let val = (self.0 >> 0usize) & 0x01;
        val != 0
    }
    #[doc = "This bit is set when a match occurs between the central 42-bits EVTIMER and the value programmed in the match-register pair. This bit is cleared by writing a '1'. Writes to clear this bit are asynchronous. It should be done before a new match value is written into the MATCH_L/H registers."]
    #[inline(always)]
    pub const fn set_OSTIMER_INTRFLAG(&mut self, val: bool) {
        self.0 = (self.0 & !(0x01 << 0usize)) | (((val as u32) & 0x01) << 0usize);
    }
    #[doc = "When this bit is '1' an interrupt/wakeup request to the domain processor will be asserted when the OSTIMER_INTR flag is set. When this bit is '0', interrupt/wakeup requests due to the OSTIMER_INTR flag are blocked."]
    #[must_use]
    #[inline(always)]
    pub const fn OSTIMER_INTENA(&self) -> bool {
        let val = (self.0 >> 1usize) & 0x01;
        val != 0
    }
    #[doc = "When this bit is '1' an interrupt/wakeup request to the domain processor will be asserted when the OSTIMER_INTR flag is set. When this bit is '0', interrupt/wakeup requests due to the OSTIMER_INTR flag are blocked."]
    #[inline(always)]
    pub const fn set_OSTIMER_INTENA(&mut self, val: bool) {
        self.0 = (self.0 & !(0x01 << 1usize)) | (((val as u32) & 0x01) << 1usize);
    }
    #[doc = "This bit will be low when it is safe to write to reload the Match Registers. In typical applications it should not be necessary to test this bit. \\[1\\]."]
    #[must_use]
    #[inline(always)]
    pub const fn MATCH_WR_RDY(&self) -> bool {
        let val = (self.0 >> 2usize) & 0x01;
        val != 0
    }
    #[doc = "This bit will be low when it is safe to write to reload the Match Registers. In typical applications it should not be necessary to test this bit. \\[1\\]."]
    #[inline(always)]
    pub const fn set_MATCH_WR_RDY(&mut self, val: bool) {
        self.0 = (self.0 & !(0x01 << 2usize)) | (((val as u32) & 0x01) << 2usize);
    }
}
impl Default for OSEVENT_CTRL {
    #[inline(always)]
    fn default() -> OSEVENT_CTRL {
        OSEVENT_CTRL(0)
    }
}
impl core::fmt::Debug for OSEVENT_CTRL {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("OSEVENT_CTRL")
            .field("OSTIMER_INTRFLAG", &self.OSTIMER_INTRFLAG())
            .field("OSTIMER_INTENA", &self.OSTIMER_INTENA())
            .field("MATCH_WR_RDY", &self.MATCH_WR_RDY())
            .finish()
    }
}
#[cfg(feature = "defmt")]
impl defmt::Format for OSEVENT_CTRL {
    fn format(&self, f: defmt::Formatter) {
        defmt::write!(
            f,
            "OSEVENT_CTRL {{ OSTIMER_INTRFLAG: {=bool:?}, OSTIMER_INTENA: {=bool:?}, MATCH_WR_RDY: {=bool:?} }}",
            self.OSTIMER_INTRFLAG(),
            self.OSTIMER_INTENA(),
            self.MATCH_WR_RDY()
        )
    }
}
