use crate::metadata::*;
pub const METADATA: Metadata = Metadata {
    name: "MCXA156",
    pins: PINS,
    peripherals: PERIPHERALS,
    interrupts: INTERRUPTS,
};
pub const PINS: &[Pin] = &[
    Pin {
        name: "P0_2",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P0_3",
        iomuxc: None,
        feature: None,
    },
    Pin {
        name: "P3_13",
        iomuxc: None,
        feature: None,
    },
];
pub const PERIPHERALS: &[Peripheral] = &[
    Peripheral {
        name: "INPUTMUX0",
        address: 0x40001000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "I3C0",
        address: 0x40002000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "I3C0Rx",
                mux: "DMA3",
                request: 7,
            },
            DmaMux {
                signal: "I3C0Tx",
                mux: "DMA3",
                request: 8,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "CTIMER0",
        address: 0x40004000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "CTIMER0M0",
                mux: "DMA3",
                request: 31,
            },
            DmaMux {
                signal: "CTIMER0M1",
                mux: "DMA3",
                request: 32,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "CTIMER1",
        address: 0x40005000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "CTIMER1M0",
                mux: "DMA3",
                request: 33,
            },
            DmaMux {
                signal: "CTIMER1M1",
                mux: "DMA3",
                request: 34,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "CTIMER2",
        address: 0x40006000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "CTIMER2M0",
                mux: "DMA3",
                request: 35,
            },
            DmaMux {
                signal: "CTIMER2M1",
                mux: "DMA3",
                request: 36,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "CTIMER3",
        address: 0x40007000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "CTIMER3M0",
                mux: "DMA3",
                request: 37,
            },
            DmaMux {
                signal: "CTIMER3M1",
                mux: "DMA3",
                request: 38,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "CTIMER4",
        address: 0x40008000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "CTIMER4M0",
                mux: "DMA3",
                request: 39,
            },
            DmaMux {
                signal: "CTIMER4M1",
                mux: "DMA3",
                request: 40,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "FREQME0",
        address: 0x40009000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "UTICK0",
        address: 0x4000B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WWDT0",
        address: 0x4000C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DMA0",
        address: 0x40080000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EDMA_0_TCD",
        address: 0x40081000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AOI0",
        address: 0x40089000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "AOI1",
        address: 0x40097000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CRC0",
        address: 0x4008A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CMC",
        address: 0x4008B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EIM0",
        address: 0x4008C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ERM0",
        address: 0x4008D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MBC0",
        address: 0x4008E000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SCG0",
        address: 0x4008F000,
        driver_name: "MCXA156/SCG::Scg",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SPC0",
        address: 0x40090000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "MRCC0",
        address: 0x40091000,
        driver_name: "MCXA156/MRCC::Mrcc",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "SYSCON",
        address: 0x40091000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GLIKEY0",
        address: 0x40091D00,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "WUU0",
        address: 0x40092000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "WUU0WakeUpEvent",
            mux: "DMA3",
            request: 1,
        }],
        gate: None,
    },
    Peripheral {
        name: "VBAT0",
        address: 0x40093000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMC0",
        address: 0x40094000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0",
        address: 0x40095000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FMU0TEST",
        address: 0x40096000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "FLEXIO0",
        address: 0x40099000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "FLEXIO0SR0",
                mux: "DMA3",
                request: 71,
            },
            DmaMux {
                signal: "FLEXIO0SR1",
                mux: "DMA3",
                request: 72,
            },
            DmaMux {
                signal: "FLEXIO0SR2",
                mux: "DMA3",
                request: 73,
            },
            DmaMux {
                signal: "FLEXIO0SR3",
                mux: "DMA3",
                request: 74,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPI2C0",
        address: 0x4009A000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPI2C0Rx",
                mux: "DMA3",
                request: 11,
            },
            DmaMux {
                signal: "LPI2C0Tx",
                mux: "DMA3",
                request: 12,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPI2C1",
        address: 0x4009B000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPI2C1Rx",
                mux: "DMA3",
                request: 13,
            },
            DmaMux {
                signal: "LPI2C1Tx",
                mux: "DMA3",
                request: 14,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPI2C2",
        address: 0x400D4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPI2C2Rx",
                mux: "DMA3",
                request: 3,
            },
            DmaMux {
                signal: "LPI2C2Tx",
                mux: "DMA3",
                request: 4,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPI2C3",
        address: 0x400D5000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPI2C3Rx",
                mux: "DMA3",
                request: 5,
            },
            DmaMux {
                signal: "LPI2C3Tx",
                mux: "DMA3",
                request: 6,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPSPI0",
        address: 0x4009C000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPSPI0Rx",
                mux: "DMA3",
                request: 15,
            },
            DmaMux {
                signal: "LPSPI0Tx",
                mux: "DMA3",
                request: 16,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPSPI1",
        address: 0x4009D000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPSPI1Rx",
                mux: "DMA3",
                request: 17,
            },
            DmaMux {
                signal: "LPSPI1Tx",
                mux: "DMA3",
                request: 18,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPUART0",
        address: 0x4009F000,
        driver_name: "MCXA156/LPUART::Lpuart",
        signals: &[
            Signal {
                name: "RXD",
                pins: &[SignalPin {
                    pin: "P0_2",
                    alt: 2u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "TXD",
                pins: &[SignalPin {
                    pin: "P0_3",
                    alt: 2u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPUART0Rx",
                mux: "DMA3",
                request: 21,
            },
            DmaMux {
                signal: "LPUART0Tx",
                mux: "DMA3",
                request: 22,
            },
        ],
        gate: Some(Gate {
            enable: "mrcc_glb_cc0",
            reset: Some("mrcc_glb_rst0"),
            config: Some("LpuartConfig"),
            bit: "lpuart0",
        }),
    },
    Peripheral {
        name: "LPUART1",
        address: 0x400A0000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPUART1Rx",
                mux: "DMA3",
                request: 23,
            },
            DmaMux {
                signal: "LPUART1Tx",
                mux: "DMA3",
                request: 24,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPUART2",
        address: 0x400A1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPUART2Rx",
                mux: "DMA3",
                request: 25,
            },
            DmaMux {
                signal: "LPUART2Tx",
                mux: "DMA3",
                request: 26,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPUART3",
        address: 0x400A2000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPUART3Rx",
                mux: "DMA3",
                request: 27,
            },
            DmaMux {
                signal: "LPUART3Tx",
                mux: "DMA3",
                request: 28,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPUART4",
        address: 0x400A3000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "LPUART4Rx",
                mux: "DMA3",
                request: 29,
            },
            DmaMux {
                signal: "LPUART4Tx",
                mux: "DMA3",
                request: 30,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "USB0",
        address: 0x400A4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "EQDC0",
        address: 0x400A7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "BUFFER",
            mux: "DMA3",
            request: 65,
        }],
        gate: None,
    },
    Peripheral {
        name: "EQDC1",
        address: 0x400A8000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "BUFFER",
            mux: "DMA3",
            request: 66,
        }],
        gate: None,
    },
    Peripheral {
        name: "FLEX_PWM0",
        address: 0x400A9000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "FlexPWM0Mcapt0",
                mux: "DMA3",
                request: 41,
            },
            DmaMux {
                signal: "FlexPWM0Mcapt1",
                mux: "DMA3",
                request: 42,
            },
            DmaMux {
                signal: "FlexPWM0Mcapt2",
                mux: "DMA3",
                request: 43,
            },
            DmaMux {
                signal: "FlexPWM0Mval0",
                mux: "DMA3",
                request: 45,
            },
            DmaMux {
                signal: "FlexPWM0Mval1",
                mux: "DMA3",
                request: 46,
            },
            DmaMux {
                signal: "FlexPWM0Mval2",
                mux: "DMA3",
                request: 47,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "FLEX_PWM1",
        address: 0x400AA000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[
            DmaMux {
                signal: "FlexPWM1Mcapt0",
                mux: "DMA3",
                request: 79,
            },
            DmaMux {
                signal: "FlexPWM1Mcapt1",
                mux: "DMA3",
                request: 80,
            },
            DmaMux {
                signal: "FlexPWM1Mcapt2",
                mux: "DMA3",
                request: 81,
            },
            DmaMux {
                signal: "FlexPWM1Mval0",
                mux: "DMA3",
                request: 83,
            },
            DmaMux {
                signal: "FlexPWM1Mval1",
                mux: "DMA3",
                request: 84,
            },
            DmaMux {
                signal: "FlexPWM1Mval2",
                mux: "DMA3",
                request: 85,
            },
        ],
        gate: None,
    },
    Peripheral {
        name: "LPTMR0",
        address: 0x400AB000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "LPTMR0CounterMatchEvent",
            mux: "DMA3",
            request: 49,
        }],
        gate: None,
    },
    Peripheral {
        name: "OSTIMER0",
        address: 0x400AD000,
        driver_name: "MCXA156/OSTIMER::Ostimer",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: Some(Gate {
            enable: "mrcc_glb_cc1",
            reset: Some("mrcc_glb_rst1"),
            config: Some("OsTimerConfig"),
            bit: "ostimer0",
        }),
    },
    Peripheral {
        name: "WAKETIMER0",
        address: 0x400AE000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "ADC0",
        address: 0x400AF000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "ADC0FifoRequest",
            mux: "DMA3",
            request: 51,
        }],
        gate: None,
    },
    Peripheral {
        name: "ADC1",
        address: 0x400B0000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "ADC1FifoRequest",
            mux: "DMA3",
            request: 52,
        }],
        gate: None,
    },
    Peripheral {
        name: "CMP0",
        address: 0x400B1000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "CMP0DmaRequest",
            mux: "DMA3",
            request: 53,
        }],
        gate: None,
    },
    Peripheral {
        name: "CMP1",
        address: 0x400B2000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "CMP1DmaRequest",
            mux: "DMA3",
            request: 54,
        }],
        gate: None,
    },
    Peripheral {
        name: "DAC0",
        address: 0x400B4000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "DAC0FifoRequest",
            mux: "DMA3",
            request: 56,
        }],
        gate: None,
    },
    Peripheral {
        name: "OPAMP0",
        address: 0x400B7000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT0",
        address: 0x400BC000,
        driver_name: "MCXA156/PORT::Port",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: Some(Gate {
            enable: "mrcc_glb_cc1",
            reset: Some("mrcc_glb_rst1"),
            config: None,
            bit: "port0",
        }),
    },
    Peripheral {
        name: "PORT1",
        address: 0x400BD000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT2",
        address: 0x400BE000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "PORT3",
        address: 0x400BF000,
        driver_name: "MCXA156/PORT::Port3",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: Some(Gate {
            enable: "mrcc_glb_cc1",
            reset: Some("mrcc_glb_rst1"),
            config: None,
            bit: "port3",
        }),
    },
    Peripheral {
        name: "PORT4",
        address: 0x400C0000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "CAN0",
        address: 0x400CC000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "CAN0",
            mux: "DMA3",
            request: 2,
        }],
        gate: None,
    },
    Peripheral {
        name: "CDOG0",
        address: 0x40100000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "DBGMAILBOX",
        address: 0x40101000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[],
        gate: None,
    },
    Peripheral {
        name: "GPIO0",
        address: 0x40102000,
        driver_name: "MCXA156/GPIO::Gpio",
        signals: &[
            Signal {
                name: "2",
                pins: &[SignalPin {
                    pin: "P0_2",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
            Signal {
                name: "3",
                pins: &[SignalPin {
                    pin: "P0_3",
                    alt: 0u8,
                    iomuxc_daisy: None,
                }],
                iomuxc_daisy: None,
            },
        ],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "GPIO0PinEvent0",
            mux: "DMA3",
            request: 60,
        }],
        gate: Some(Gate {
            enable: "mrcc_glb_cc1",
            reset: Some("mrcc_glb_rst1"),
            config: None,
            bit: "gpio0",
        }),
    },
    Peripheral {
        name: "GPIO1",
        address: 0x40103000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "GPIO1PinEvent0",
            mux: "DMA3",
            request: 61,
        }],
        gate: None,
    },
    Peripheral {
        name: "GPIO2",
        address: 0x40104000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "GPIO2PinEvent0",
            mux: "DMA3",
            request: 62,
        }],
        gate: None,
    },
    Peripheral {
        name: "GPIO3",
        address: 0x40105000,
        driver_name: "MCXA156/GPIO::Gpio",
        signals: &[Signal {
            name: "13",
            pins: &[SignalPin {
                pin: "P3_13",
                alt: 0u8,
                iomuxc_daisy: None,
            }],
            iomuxc_daisy: None,
        }],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "GPIO3PinEvent0",
            mux: "DMA3",
            request: 63,
        }],
        gate: Some(Gate {
            enable: "mrcc_glb_cc1",
            reset: Some("mrcc_glb_rst1"),
            config: None,
            bit: "gpio3",
        }),
    },
    Peripheral {
        name: "GPIO4",
        address: 0x40106000,
        driver_name: "",
        signals: &[],
        flexcomm: None,
        dma_muxing: &[DmaMux {
            signal: "GPIO4PinEvent0",
            mux: "DMA3",
            request: 64,
        }],
        gate: None,
    },
];
pub const INTERRUPTS: &[(&str, u32)] = &[
    ("RESERVED16", 0u32),
    ("CMC", 1u32),
    ("DMA_CH0", 2u32),
    ("DMA_CH1", 3u32),
    ("DMA_CH2", 4u32),
    ("DMA_CH3", 5u32),
    ("DMA_CH4", 6u32),
    ("DMA_CH5", 7u32),
    ("DMA_CH6", 8u32),
    ("DMA_CH7", 9u32),
    ("ERM0_SINGLE_BIT", 10u32),
    ("ERM0_MULTI_BIT", 11u32),
    ("FMU0", 12u32),
    ("GLIKEY0", 13u32),
    ("MBC0", 14u32),
    ("SCG0", 15u32),
    ("SPC0", 16u32),
    ("VBAT0", 17u32),
    ("WUU0", 18u32),
    ("CAN0", 19u32),
    ("RESERVED36", 20u32),
    ("RESERVED37", 21u32),
    ("RESERVED38", 22u32),
    ("FLEXIO", 23u32),
    ("I3C0", 24u32),
    ("RESERVED41", 25u32),
    ("LPI2C0", 26u32),
    ("LPI2C1", 27u32),
    ("LPSPI0", 28u32),
    ("LPSPI1", 29u32),
    ("RESERVED46", 30u32),
    ("LPUART0", 31u32),
    ("LPUART1", 32u32),
    ("LPUART2", 33u32),
    ("LPUART3", 34u32),
    ("LPUART4", 35u32),
    ("USB0", 36u32),
    ("RESERVED53", 37u32),
    ("CDOG0", 38u32),
    ("CTIMER0", 39u32),
    ("CTIMER1", 40u32),
    ("CTIMER2", 41u32),
    ("CTIMER3", 42u32),
    ("CTIMER4", 43u32),
    ("FLEXPWM0_RELOAD_ERROR", 44u32),
    ("FLEXPWM0_FAULT", 45u32),
    ("FLEXPWM0_SUBMODULE0", 46u32),
    ("FLEXPWM0_SUBMODULE1", 47u32),
    ("FLEXPWM0_SUBMODULE2", 48u32),
    ("RESERVED65", 49u32),
    ("QDC0_COMPARE", 50u32),
    ("QDC0_HOME", 51u32),
    ("QDC0_WATCHDOG", 52u32),
    ("QDC0_INDEX", 53u32),
    ("FREQME0", 54u32),
    ("LPTMR0", 55u32),
    ("RESERVED72", 56u32),
    ("OS_EVENT", 57u32),
    ("WAKETIMER0", 58u32),
    ("UTICK0", 59u32),
    ("WWDT0", 60u32),
    ("RESERVED77", 61u32),
    ("ADC0", 62u32),
    ("ADC1", 63u32),
    ("CMP0", 64u32),
    ("CMP1", 65u32),
    ("RESERVED82", 66u32),
    ("DAC0", 67u32),
    ("RESERVED84", 68u32),
    ("RESERVED85", 69u32),
    ("RESERVED86", 70u32),
    ("GPIO0", 71u32),
    ("GPIO1", 72u32),
    ("GPIO2", 73u32),
    ("GPIO3", 74u32),
    ("GPIO4", 75u32),
    ("RESERVED92", 76u32),
    ("LPI2C2", 77u32),
    ("LPI2C3", 78u32),
    ("FLEXPWM1_RELOAD_ERROR", 79u32),
    ("FLEXPWM1_FAULT", 80u32),
    ("FLEXPWM1_SUBMODULE0", 81u32),
    ("FLEXPWM1_SUBMODULE1", 82u32),
    ("FLEXPWM1_SUBMODULE2", 83u32),
    ("RESERVED100", 84u32),
    ("QDC1_COMPARE", 85u32),
    ("QDC1_HOME", 86u32),
    ("QDC1_WATCHDOG", 87u32),
    ("QDC1_INDEX", 88u32),
];
