name: ci
on:
  push:
    branches: [ "main" ]
  pull_request:
  merge_group:

env:
  CARGO_TERM_COLOR: always

jobs:
  check-generator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.9.1
      - name: Check
        run: |
          cargo check -p generator --locked
      - name: Clippy
        run: |
          cargo clippy -p generator --locked -- -D warnings

  # Check if we can still generate code for all PACs (do not commit changes)
  run-generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Get Submodule commit
        id: get-submodule-commit
        run: |
          echo "commit=$(git submodule status -- data/mcux-soc-svd/ | cut -c2- | cut -f 1 -d " ")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache submodules
        id: cache-submodules
        uses: actions/cache@v5
        with:
          path: data/mcux-soc-svd/
          key: ${{ steps.get-submodule-commit.outputs.commit }}-mcux-soc-svd
        # Checkout of submodules can take 90 seconds, so we try to cache
      - name: Checkout submodules
        if: steps.cache-submodules.outputs.cache-hit != 'true'
        run: |
          git submodule update --init --recursive --force --depth=1 --checkout data/mcux-soc-svd
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.9.1
      - name: Install Dependencies
        run: |
          cargo install form
      - name: Run generate on all chips
        run: |
          cargo run -p generator --locked -- generate
      - name: Check generated output is current
        run: |
          test -z "$(git status --porcelain=v1 --untracked-files=all -- nxp-pac)"

  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        chip:
          - mimxrt1011
          - mimxrt1062
          - mimxrt1064
          - mimxrt685s_cm33
          - mcxn947_cm33_core0
          - mcxn947_cm33_core1
          - mcxa256
          - mcxa577
          - lpc55s16
          - lpc55s69_cm33_core0
          - lpc55s69_cm33_core1
    steps:
      - uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.9.1
      - name: Check
        run: |
          cargo check -p nxp-pac --locked --features ${{ matrix.chip }}
  check-metadata:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        chip:
          - mimxrt1011
          - mimxrt1062
          - mimxrt1064
          - mcxa256
          - mcxa577
          - lpc55s16
          - lpc55s69_cm33_core0
          - lpc55s69_cm33_core1
    steps:
      - uses: actions/checkout@v6
      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v2.9.1
      - name: Check
        run: |
          cargo check -p nxp-pac --locked --features ${{ matrix.chip }},metadata
